package com.jarvis.assistant.commands.router

data class CommandIntent(
    val command: CommandType,
    val confidence: Float,
    val parameters: Map<String, String> = emptyMap(),
    val rawInput: String
)

enum class CommandType {
    TIMER,
    CALCULATOR,
    REMINDER,
    TIME,
    OPEN_APP,
    WEATHER,
    NOTE,
    UNIT_CONVERSION,
    TRANSLATION,
    SEARCH,
    CONTACT,
    ALARM,
    CALENDAR,
    MUSIC,
    DEVICE_INFO,
    BATTERY,
    NETWORK,
    FLASHLIGHT,
    SCREENSHOT,
    APP_LAUNCH,
    SEND_MESSAGE,
    CALL,
    SETTINGS,
    LOCATION,
    SPEED_TEST,
    RANDOM,
    DATE,
    JOKE,
    QUOTE,
    MATH,
    NAVIGATION,
    EMAIL,
    SOCIAL_MEDIA,
    NEWS,
    STOCK,
    CRYPTO,
    LANGUAGE_DETECT,
    SUMMARIZE,
    SPELL_CHECK,
    GRAMMAR_CHECK,
    SENTIMENT,
    KEYWORD_EXTRACT,
    URL_SHORTENER,
    QR_CODE,
    BARCODE,
    IMAGE_SEARCH,
    VOICE_NOTE,
    EXPENSE,
    BUDGET,
    RECIPE,
    FITNESS,
    WATER_TRACKER,
    SLEEP_TRACKER,
    MOOD_TRACKER,
    HABIT_TRACKER,
    GOAL_TRACKER,
    BOOK,
    MOVIE,
    TV_SHOW,
    GAME,
    SPORTS,
    FLIGHT,
    HOTEL,
    RESTAURANT,
    SHOPPING,
    NEWS_ARTICLE,
    PODCAST,
    AUDIOBOOK,
    LYRICS,
    TRIVIA,
    RIDDLE,
    FACT,
    HOROSCOPE,
    BIRTHDAY,
    ANNIVERSARY,
    COUNTDOWN,
    PASSWORD_GENERATOR,
    HASH,
    ENCRYPT,
    BASE64,
    NONE
}

data class CommandResult(
    val success: Boolean,
    val response: String,
    val action: (() -> Unit)? = null
)
